project:
  type: website
  output-dir: docs

website:
  title: "Saratessa Palos MA BCBA LBA"  
  navbar:
    left: []  
    right:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: CV_PalosS.pdf  
      - href: "https://bsky.app/profile/saratessa.bsky.social"
        text: "Bluesky"
      - icon: github
        href: "https://github.com/saratessa"
  page-footer:
    center: "© 2025 Saratessa Palos | Santino Consulting"

format:
  html:
    theme: jolla
    css: custom.css
    includes:
      in-header: _navbar.html

editor: visual
