project:
  type: website

website:
  title: "Saratessa Palos MA BCBA LBA"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: CV_PalosS.pdf  
    right:
      - icon: Blue Sky
        href: "https://bsky.app/profile/saratessa.bsky.social"
      - icon: github
        href: "https://github.com/saratessa"
  page-footer:
    center: "© 2025 Saratessa Palos | Powered by Quarto"
    
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

